name: Pre-commit Checks

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: |
          PYTHONPATH=${{ github.workspace }} uv run pytest tests/ -v

      - name: Check for type errors
        run: |
          uv run mypy planning/
